version: "3.8"

services:

  configserver:
    image: xueyudarren/ms-configserver:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - xueyudarren-network

  eurekaserver:
    image: xueyudarren/ms-eurekaserver:latest
    mem_limit: 700m
    ports:
      - "8091:8091"
    networks:
      - xueyudarren-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8090/

  accounts:
    image: xueyudarren/ms-accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - xueyudarren-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8090/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8091/eureka/

  loans:
    image: xueyudarren/ms-loans:latest
    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - xueyudarren-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8090/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8091/eureka/

  cards:
    image: xueyudarren/ms-cards:latest
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      - xueyudarren-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8090/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8091/eureka/

  gatewayserver:
    image: xueyudarren/ms-gatewayserver:latest
    mem_limit: 700m
    ports:
      - "8072:8072"
    networks:
      - xueyudarren-network
    depends_on:
      - configserver
      - eurekaserver
      - cards
      - loans
      - accounts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8090/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8091/eureka/

networks:
  xueyudarren-network:
    driver: bridge
